# Generated by Django 5.2 on 2025-06-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercategory',
            name='budget_of_teams',
            field=models.IntegerField(default=10000),
        ),
    ]
