# Generated by Django 5.2 on 2025-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='expense_budget',
            field=models.IntegerField(default=10000),
        ),
    ]
