# Generated by Django 5.1.6 on 2025-04-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('team', 'Team'), ('authority', 'Authority')], max_length=20),
        ),
    ]
