# Generated by Django 5.2 on 2025-04-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gender',
        ),
        migrations.AlterField(
            model_name='player',
            name='playing_position',
            field=models.CharField(choices=[('Midfielder', 'Midfielder'), ('Goalkeeper', 'Goalkeeper'), ('Forward', 'Forward'), ('Defender', 'Defender')], max_length=20),
        ),
    ]
