# Generated by Django 5.1.6 on 2025-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_player_gender_alter_player_playing_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assigned_team',
            field=models.CharField(default='Not bought yet', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
