# Generated by Django 5.1.6 on 2025-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_assigned_team_player_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
