# Generated by Django 5.2 on 2025-06-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
