# Generated by Django 5.2 on 2025-05-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
    ]
