# Generated by Django 5.1.6 on 2025-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_player_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_class',
            field=models.CharField(blank=True, choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], max_length=1, null=True),
        ),
    ]
