# Generated by Django 5.1.6 on 2025-06-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_player_price'),
        ('player', '0006_player_player_class'),
    ]

    operations = [
    ]
