# Generated by Django 5.1.6 on 2025-06-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_alter_player_assigned_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assigned_team',
            field=models.CharField(default='Not bought yet', max_length=100),
        ),
    ]
