# Generated by Django 5.2 on 2025-06-09 22:02

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('player_duration', models.DurationField(default=datetime.timedelta(seconds=20))),
            ],
        ),
    ]
