# Generated by Django 5.2 on 2025-06-22 12:17

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsettings',
            name='player_current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auctionsettings',
            name='player_default_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=20)),
        ),
        migrations.AddField(
            model_name='auctionsettings',
            name='player_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auctionsettings',
            name='player_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
