# Generated by Django 5.2 on 2025-06-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auctionsettings_player_current_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionsettings',
            old_name='player_end_time',
            new_name='auction_end_time',
        ),
    ]
