# Generated by Django 5.2 on 2025-06-22 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_rename_player_end_time_auctionsettings_auction_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsettings',
            name='auction_increase_time',
            field=models.DurationField(default=datetime.timedelta(seconds=10)),
        ),
    ]
