# Generated by Django 5.2.17 on 2026-09-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auctionsettings_auction_increase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsettings',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctionsettings',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]