# Generated by Django 5.2.17 on 2026-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_auctionsettings_is_paused_auctionsettings_paused_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsettings',
            name='starting_budget',
            field=models.IntegerField(default=0),
        ),
    ]