# Generated by Django 6.1.1 on 2026-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_auctionsettings_starting_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionsettings',
            name='starting_budget',
            field=models.IntegerField(default=1000),
        ),
    ]
